---
apiVersion: v1
kind: Namespace
metadata:
  name: mlflow
---
# Source: mlflow-server/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-mlflow-server
  namespace: mlflow
  labels:
    helm.sh/chart: mlflow-server-0.6.2
    app.kubernetes.io/name: mlflow-server
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "2.6"
    app.kubernetes.io/managed-by: Helm
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"release-name-mlflow-server"}}'
---
# Source: mlflow-server/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-mlflow-server
  namespace: mlflow
  annotations:
     service.alpha.openshift.io/serving-cert-secret-name: release-name-mlflow-server-tls
  labels:
    helm.sh/chart: mlflow-server-0.6.2
    app.kubernetes.io/name: mlflow-server
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "2.6"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: mlflow-server
      protocol: TCP
      name: mlflow-server
    - port: 8443
      targetPort: oauth-proxy
      protocol: TCP
      name: oauth
  selector:
    app.kubernetes.io/name: mlflow-server
    app.kubernetes.io/instance: release-name
---
# Source: mlflow-server/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-mlflow-server
  namespace: mlflow
  annotations:
    app.openshift.io/vcs-uri: github.com/strangiato/mlflow-server
  labels:
    helm.sh/chart: mlflow-server-0.6.2
    app.kubernetes.io/name: mlflow-server
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "2.6"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mlflow-server
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mlflow-server
        app.kubernetes.io/instance: release-name
    spec:
      serviceAccountName: release-name-mlflow-server
      securityContext:
        {}
      containers:
        - name: mlflow-server
          securityContext:
            {}
          image: "quay.io/troyer/mlflow-server:2.6"
          imagePullPolicy: IfNotPresent
          ports:
            - name: mlflow-server
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: mlflow-server
          readinessProbe:
            httpGet:
              path: /health
              port: mlflow-server
            initialDelaySeconds: 30
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: release-name-mlflow-server
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: release-name-mlflow-server
                  key: AWS_SECRET_ACCESS_KEY
            - name: MLFLOW_S3_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: release-name-mlflow-server
                  key: BUCKET_NAME
            
            - name: BUCKET_HOST
              valueFrom:
                configMapKeyRef:
                  name: release-name-mlflow-server
                  key: BUCKET_HOST
            - name: BUCKET_PORT
              valueFrom:
                configMapKeyRef:
                  name: release-name-mlflow-server
                  key: BUCKET_PORT
            - name: MLFLOW_S3_ENDPOINT_URL
              value: 'https://$(BUCKET_HOST):$(BUCKET_PORT)'
            
            - name: AWS_CA_BUNDLE
              value: /run/secrets/kubernetes.io/serviceaccount/service-ca.crt
            
            - name: PGBOUNCE_HOST
              valueFrom:
                secretKeyRef:
                  name: release-name-pguser-release-name
                  key: pgbouncer-host
            - name: PGBOUNCE_PORT
              valueFrom:
                secretKeyRef:
                  name: release-name-pguser-release-name
                  key: pgbouncer-port
            - name: MLFLOW_DATABASE_HOST
              value: $(PGBOUNCE_HOST):$(PGBOUNCE_PORT)
            - name: MLFLOW_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: release-name-pguser-release-name
                  key: dbname
            - name: MLFLOW_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: release-name-pguser-release-name
                  key: password
            - name: MLFLOW_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: release-name-pguser-release-name
                  key: us
